FROM eclipse-temurin:17-jdk-jammy AS build
WORKDIR /workspace/app
COPY . .
RUN ./mvnw clean package

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=build /workspace/app/target/curriculo-api-*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]